In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Churn.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Surname'] = label_encoder.fit_transform(df['Surname'])

In [7]:
df.head(3)

RowNumber  CustomerId  Surname  CreditScore Geography  Gender  Age  Tenure  \
0          1    15634602     1115          619    France  Female   42       2   
1          2    15647311     1177          608     Spain  Female   41       1   
2          3    15619304     2040          502    France  Female   42       8   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   

   Exited  
0       1  
1       0  
2       1

In [8]:
df['Geography']= label_encoder.fit_transform(df['Geography'])
df['Gender']= label_encoder.fit_transform(df['Gender'])

In [9]:
df.head(3)

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602     1115          619          0       0   42   
1          2    15647311     1177          608          2       0   41   
2          3    15619304     2040          502          0       0   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [10]:
df.corr()

RowNumber  CustomerId   Surname  CreditScore  Geography  \
RowNumber         1.000000    0.004202  0.001682     0.005840  -0.010358   
CustomerId        0.004202    1.000000  0.005689     0.005308   0.006516   
Surname           0.001682    0.005689  1.000000     0.007489  -0.022878   
CreditScore       0.005840    0.005308  0.007489     1.000000   0.007888   
Geography        -0.010358    0.006516 -0.022878     0.007888   1.000000   
Gender            0.018196   -0.002641 -0.002049    -0.002857   0.004719   
Age               0.000783    0.009497  0.005550    -0.003965   0.022812   
Tenure           -0.006495   -0.014883 -0.017412     0.000842   0.003739   
Balance          -0.009067   -0.012419  0.002657     0.006268   0.069408   
NumOfProducts     0.007246    0.016972 -0.016460     0.012238   0.003972   
HasCrCard         0.000599   -0.014025 -0.008993    -0.005458  -0.008523   
IsActiveMember    0.012044    0.001665  0.001483     0.025651   0.006724   
EstimatedSalary  -0.005988    0.015271  0.011850    -0.001384  -0.001369   
Exited           -0.016571   -0.006248 -0.010822    -0.027094   0.035943   

                   Gender       Age    Tenure   Balance  NumOfProducts  \
RowNumber        0.018196  0.000783 -0.006495 -0.009067       0.007246   
CustomerId      -0.002641  0.009497 -0.014883 -0.012419       0.016972   
Surname         -0.002049  0.005550 -0.017412  0.002657      -0.016460   
CreditScore     -0.002857 -0.003965  0.000842  0.006268       0.012238   
Geography        0.004719  0.022812  0.003739  0.069408       0.003972   
Gender           1.000000 -0.027544  0.014733  0.012087      -0.021859   
Age             -0.027544  1.000000 -0.009997  0.028308      -0.030680   
Tenure           0.014733 -0.009997  1.000000 -0.012254       0.013444   
Balance          0.012087  0.028308 -0.012254  1.000000      -0.304180   
NumOfProducts   -0.021859 -0.030680  0.013444 -0.304180       1.000000   
HasCrCard        0.005766 -0.011721  0.022583 -0.014858       0.003183   
IsActiveMember   0.022544  0.085472 -0.028362 -0.010084       0.009612   
EstimatedSalary -0.008112 -0.007201  0.007784  0.012797       0.014204   
Exited          -0.106512  0.285323 -0.014001  0.118533      -0.047820   

                 HasCrCard  IsActiveMember  EstimatedSalary    Exited  
RowNumber         0.000599        0.012044        -0.005988 -0.016571  
CustomerId       -0.014025        0.001665         0.015271 -0.006248  
Surname          -0.008993        0.001483         0.011850 -0.010822  
CreditScore      -0.005458        0.025651        -0.001384 -0.027094  
Geography        -0.008523        0.006724        -0.001369  0.035943  
Gender            0.005766        0.022544        -0.008112 -0.106512  
Age              -0.011721        0.085472        -0.007201  0.285323  
Tenure            0.022583       -0.028362         0.007784 -0.014001  
Balance          -0.014858       -0.010084         0.012797  0.118533  
NumOfProducts     0.003183        0.009612         0.014204 -0.047820  
HasCrCard         1.000000       -0.011866        -0.009933 -0.007138  
IsActiveMember   -0.011866        1.000000        -0.011421 -0.156128  
EstimatedSalary  -0.009933       -0.011421         1.000000  0.012097  
Exited           -0.007138       -0.156128         0.012097  1.000000

In [11]:
df.drop(['RowNumber', 'CustomerId','Surname','CreditScore','NumOfProducts','HasCrCard'], axis =1)

Geography  Gender  Age  Tenure    Balance  IsActiveMember  \
0             0       0   42       2       0.00               1   
1             2       0   41       1   83807.86               1   
2             0       0   42       8  159660.80               0   
3             0       0   39       1       0.00               0   
4             2       0   43       2  125510.82               1   
...         ...     ...  ...     ...        ...             ...   
9995          0       1   39       5       0.00               0   
9996          0       1   35      10   57369.61               1   
9997          0       0   36       7       0.00               1   
9998          1       1   42       3   75075.31               0   
9999          0       0   28       4  130142.79               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 8 columns]

In [12]:
X = df.drop("Exited", axis =1)
Y = df['Exited']

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=12345)

In [14]:
def build_DT():
    from sklearn.tree import DecisionTreeClassifier
    model = DecisionTreeClassifier()
    model.fit(x_train, y_train)
    return model

In [15]:
def build_RF():
    from sklearn.ensemble import RandomForestClassifier
    model = RandomForestClassifier()
    model.fit(x_train, y_train)
    return model

In [16]:
def build_CB():
    from catboost import CatBoostClassifier
    model = CatBoostClassifier()
    model.fit(x_train, y_train)
    return model

In [17]:
def build_XGB():
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

In [18]:
DT_model = build_DT()
RF_model = build_RF()
CB_model = build_CB()
XGB_model = build_XGB()

Learning rate set to 0.023648
0:	learn: 0.6739464	total: 154ms	remaining: 2m 34s
1:	learn: 0.6558381	total: 162ms	remaining: 1m 20s
2:	learn: 0.6387490	total: 169ms	remaining: 56.3s
3:	learn: 0.6244572	total: 177ms	remaining: 44s
4:	learn: 0.6096426	total: 184ms	remaining: 36.7s
5:	learn: 0.5960932	total: 193ms	remaining: 31.9s
6:	learn: 0.5853831	total: 201ms	remaining: 28.5s
7:	learn: 0.5739083	total: 208ms	remaining: 25.8s
8:	learn: 0.5612764	total: 217ms	remaining: 23.9s
9:	learn: 0.5500172	total: 226ms	remaining: 22.4s
10:	learn: 0.5378297	total: 235ms	remaining: 21.2s
11:	learn: 0.5279093	total: 243ms	remaining: 20s
12:	learn: 0.5169692	total: 251ms	remaining: 19.1s
13:	learn: 0.5088923	total: 259ms	remaining: 18.3s
14:	learn: 0.5009298	total: 267ms	remaining: 17.5s
15:	learn: 0.4930027	total: 275ms	remaining: 16.9s
16:	learn: 0.4854628	total: 282ms	remaining: 16.3s
17:	learn: 0.4776134	total: 290ms	remaining: 15.8s
18:	learn: 0.4715179	total: 298ms	remaining: 15.4s
19:	learn: 0.

C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score
def evaluation(model):
    y_true = y_test
    y_pred = model.predict(x_test)
    cm = confusion_matrix(y_true, y_pred)
    print(cm)
    print(f"accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%")
    print(f"precesion = {precision_score(y_true, y_pred)*100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred)*100:.2f}%")
    print(f"f1_score = {f1_score(y_true, y_pred)*100:.2f}%")

In [20]:
evaluation(DT_model)

[[2035  339]
 [ 329  297]]
accuracy = 77.73%
precesion = 46.70%
recall = 47.44%
f1_score = 47.07%


In [21]:
evaluation(RF_model)

[[2307   67]
 [ 371  255]]
accuracy = 85.40%
precesion = 79.19%
recall = 40.73%
f1_score = 53.80%


In [22]:
evaluation(CB_model)

[[2285   89]
 [ 346  280]]
accuracy = 85.50%
precesion = 75.88%
recall = 44.73%
f1_score = 56.28%


In [23]:
evaluation(XGB_model)

[[2240  134]
 [ 351  275]]
accuracy = 83.83%
precesion = 67.24%
recall = 43.93%
f1_score = 53.14%


C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.