In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('claimants.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   ATTORNEY  1340 non-null   int64  
 1   CLMSEX    1328 non-null   float64
 2   CLMINSUR  1299 non-null   float64
 3   SEATBELT  1292 non-null   float64
 4   CLMAGE    1151 non-null   float64
 5   LOSS      1340 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 62.9 KB


In [4]:
df.isna().sum()

ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.head(3)
df.isna().sum()

ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [7]:
df.corr()

ATTORNEY    CLMSEX  CLMINSUR  SEATBELT    CLMAGE      LOSS
ATTORNEY  1.000000  0.097475  0.084609 -0.060795  0.001132 -0.225769
CLMSEX    0.097475  1.000000  0.058164 -0.017814 -0.017942 -0.029742
CLMINSUR  0.084609  0.058164  1.000000  0.021217  0.048166  0.019502
SEATBELT -0.060795 -0.017814  0.021217  1.000000 -0.028343  0.131182
CLMAGE    0.001132 -0.017942  0.048166 -0.028343  1.000000  0.065513
LOSS     -0.225769 -0.029742  0.019502  0.131182  0.065513  1.000000

In [8]:
X = df.drop("ATTORNEY", axis =1)
Y = df['ATTORNEY']

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=12345)

In [10]:
def build_DT():
    from sklearn.tree import DecisionTreeClassifier
    model = DecisionTreeClassifier()
    model.fit(x_train, y_train)
    return model

In [11]:
def build_RF():
    from sklearn.ensemble import RandomForestClassifier
    model = RandomForestClassifier()
    model.fit(x_train, y_train)
    return model

In [12]:
def build_CB():
    from catboost import CatBoostClassifier
    model = CatBoostClassifier()
    model.fit(x_train, y_train)
    return model

In [13]:
def build_XGB():
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

In [14]:
DT_model = build_DT()
RF_model = build_RF()
CB_model = build_CB()
XGB_model = build_XGB()

Learning rate set to 0.009199
0:	learn: 0.6911189	total: 149ms	remaining: 2m 28s
1:	learn: 0.6888789	total: 152ms	remaining: 1m 15s
2:	learn: 0.6867616	total: 155ms	remaining: 51.5s
3:	learn: 0.6846188	total: 158ms	remaining: 39.4s
4:	learn: 0.6826745	total: 162ms	remaining: 32.2s
5:	learn: 0.6805830	total: 165ms	remaining: 27.3s
6:	learn: 0.6784253	total: 169ms	remaining: 23.9s
7:	learn: 0.6767222	total: 171ms	remaining: 21.2s
8:	learn: 0.6750040	total: 174ms	remaining: 19.1s
9:	learn: 0.6727196	total: 177ms	remaining: 17.5s
10:	learn: 0.6708104	total: 181ms	remaining: 16.2s
11:	learn: 0.6687422	total: 184ms	remaining: 15.2s
12:	learn: 0.6669002	total: 187ms	remaining: 14.2s
13:	learn: 0.6653560	total: 190ms	remaining: 13.4s
14:	learn: 0.6633993	total: 194ms	remaining: 12.7s
15:	learn: 0.6617123	total: 198ms	remaining: 12.2s
16:	learn: 0.6598785	total: 201ms	remaining: 11.6s
17:	learn: 0.6587120	total: 204ms	remaining: 11.1s
18:	learn: 0.6570153	total: 208ms	remaining: 10.7s
19:	learn

C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score
def evaluation(model):
    y_true = y_test
    y_pred = model.predict(x_test)
    cm = confusion_matrix(y_true, y_pred)
    print(cm)
    print(f"accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%")
    print(f"precesion = {precision_score(y_true, y_pred)*100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred)*100:.2f}%")
    print(f"f1_score = {f1_score(y_true, y_pred)*100:.2f}%")

In [16]:
evaluation(DT_model)

[[117  64]
 [ 64  84]]
accuracy = 61.09%
precesion = 56.76%
recall = 56.76%
f1_score = 56.76%


In [17]:
evaluation(RF_model)

[[126  55]
 [ 50  98]]
accuracy = 68.09%
precesion = 64.05%
recall = 66.22%
f1_score = 65.12%


In [18]:
evaluation(CB_model)

[[139  42]
 [ 43 105]]
accuracy = 74.16%
precesion = 71.43%
recall = 70.95%
f1_score = 71.19%


In [19]:
evaluation(XGB_model)

[[121  60]
 [ 49  99]]
accuracy = 66.87%
precesion = 62.26%
recall = 66.89%
f1_score = 64.50%


C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.