In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('framingham.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4240 non-null   int64  
 1   age              4240 non-null   int64  
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64  
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64  
 7   prevalentHyp     4240 non-null   int64  
 8   diabetes         4240 non-null   int64  
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 530.1 KB


In [4]:
df.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.head(3)
df.isna().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [7]:
df.corr()

male       age  education  currentSmoker  cigsPerDay  \
male             1.000000 -0.024412   0.017729       0.206114    0.330322   
age             -0.024412  1.000000  -0.159499      -0.210771   -0.189295   
education        0.017729 -0.159499   1.000000       0.025251    0.013790   
currentSmoker    0.206114 -0.210771   0.025251       1.000000    0.773913   
cigsPerDay       0.330322 -0.189295   0.013790       0.773913    1.000000   
BPMeds          -0.052124  0.134732  -0.013739      -0.051923   -0.046504   
prevalentStroke -0.002312  0.050893  -0.030386      -0.038150   -0.036286   
prevalentHyp     0.001424  0.306239  -0.078828      -0.108078   -0.070460   
diabetes         0.013819  0.109092  -0.039627      -0.041849   -0.036961   
totChol         -0.070321  0.268252  -0.013522      -0.051034   -0.030400   
sysBP           -0.045358  0.388267  -0.124360      -0.134428   -0.094781   
diaBP            0.051872  0.208283  -0.058059      -0.115955   -0.056746   
BMI              0.073111  0.137511  -0.137555      -0.159821   -0.087395   
heartRate       -0.115285 -0.002722  -0.064214       0.050841    0.064030   
glucose          0.002940  0.118349  -0.031998      -0.053242   -0.053726   
TenYearCHD       0.091688  0.233983  -0.063279       0.019165    0.052014   

                   BPMeds  prevalentStroke  prevalentHyp  diabetes   totChol  \
male            -0.052124        -0.002312      0.001424  0.013819 -0.070321   
age              0.134732         0.050893      0.306239  0.109092  0.268252   
education       -0.013739        -0.030386     -0.078828 -0.039627 -0.013522   
currentSmoker   -0.051923        -0.038150     -0.108078 -0.041849 -0.051034   
cigsPerDay      -0.046504        -0.036286     -0.070460 -0.036961 -0.030400   
BPMeds           1.000000         0.113125      0.262910  0.049066  0.094083   
prevalentStroke  0.113125         1.000000      0.066057  0.009625  0.012736   
prevalentHyp     0.262910         0.066057      1.000000  0.080556  0.166655   
diabetes         0.049066         0.009625      0.080556  1.000000  0.048451   
totChol          0.094083         0.012736      0.166655  0.048451  1.000000   
sysBP            0.271263         0.061070      0.697675  0.102552  0.219925   
diaBP            0.199630         0.055834      0.617734  0.050686  0.174422   
BMI              0.105642         0.036496      0.302949  0.089009  0.121056   
heartRate        0.012889        -0.017019      0.146818  0.060984  0.093053   
glucose          0.054232         0.016061      0.086942  0.614820  0.049884   
TenYearCHD       0.089152         0.048366      0.181387  0.093431  0.091338   

                    sysBP     diaBP       BMI  heartRate   glucose  TenYearCHD  
male            -0.045358  0.051872  0.073111  -0.115285  0.002940    0.091688  
age              0.388267  0.208283  0.137511  -0.002722  0.118349    0.233983  
education       -0.124360 -0.058059 -0.137555  -0.064214 -0.031998   -0.063279  
currentSmoker   -0.134428 -0.115955 -0.159821   0.050841 -0.053242    0.019165  
cigsPerDay      -0.094781 -0.056746 -0.087395   0.064030 -0.053726    0.052014  
BPMeds           0.271263  0.199630  0.105642   0.012889  0.054232    0.089152  
prevalentStroke  0.061070  0.055834  0.036496  -0.017019  0.016061    0.048366  
prevalentHyp     0.697675  0.617734  0.302949   0.146818  0.086942    0.181387  
diabetes         0.102552  0.050686  0.089009   0.060984  0.614820    0.093431  
totChol          0.219925  0.174422  0.121056   0.093053  0.049884    0.091338  
sysBP            1.000000  0.786669  0.330917   0.184797  0.134651    0.222821  
diaBP            0.786669  1.000000  0.385348   0.178744  0.063540    0.150124  
BMI              0.330917  0.385348  1.000000   0.074131  0.083683    0.082055  
heartRate        0.184797  0.178744  0.074131   1.000000  0.097074    0.020514  
glucose          0.134651  0.063540  0.083683   0.097074  1.000000    0.121990  
TenYearCHD       0.222821  0.150124  0.082055   0.0205

In [8]:
X = df.drop("TenYearCHD", axis =1)
Y = df['TenYearCHD']

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=12345)

In [10]:
def build_DT():
    from sklearn.tree import DecisionTreeClassifier
    model = DecisionTreeClassifier()
    model.fit(x_train, y_train)
    return model

In [11]:
def build_RF():
    from sklearn.ensemble import RandomForestClassifier
    model = RandomForestClassifier()
    model.fit(x_train, y_train)
    return model

In [12]:
def build_CB():
    from catboost import CatBoostClassifier
    model = CatBoostClassifier()
    model.fit(x_train, y_train)
    return model

In [13]:
def build_XGB():
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

In [14]:
DT_model = build_DT()
RF_model = build_RF()
CB_model = build_CB()
XGB_model = build_XGB()

Learning rate set to 0.01539
0:	learn: 0.6831836	total: 150ms	remaining: 2m 29s
1:	learn: 0.6726267	total: 155ms	remaining: 1m 17s
2:	learn: 0.6631949	total: 160ms	remaining: 53.2s
3:	learn: 0.6530344	total: 165ms	remaining: 41.2s
4:	learn: 0.6431428	total: 171ms	remaining: 34s
5:	learn: 0.6341827	total: 176ms	remaining: 29.2s
6:	learn: 0.6253315	total: 182ms	remaining: 25.8s
7:	learn: 0.6166489	total: 187ms	remaining: 23.2s
8:	learn: 0.6089499	total: 191ms	remaining: 21.1s
9:	learn: 0.6013115	total: 197ms	remaining: 19.5s
10:	learn: 0.5935430	total: 202ms	remaining: 18.2s
11:	learn: 0.5859456	total: 208ms	remaining: 17.1s
12:	learn: 0.5788718	total: 214ms	remaining: 16.2s
13:	learn: 0.5728720	total: 219ms	remaining: 15.4s
14:	learn: 0.5672088	total: 225ms	remaining: 14.8s
15:	learn: 0.5613729	total: 231ms	remaining: 14.2s
16:	learn: 0.5555400	total: 238ms	remaining: 13.7s
17:	learn: 0.5494746	total: 244ms	remaining: 13.3s
18:	learn: 0.5439943	total: 250ms	remaining: 12.9s
19:	learn: 0

C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score
def evaluation(model):
    y_true = y_test
    y_pred = model.predict(x_test)
    cm = confusion_matrix(y_true, y_pred)
    print(cm)
    print(f"accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%")
    print(f"precesion = {precision_score(y_true, y_pred)*100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred)*100:.2f}%")
    print(f"f1_score = {f1_score(y_true, y_pred)*100:.2f}%")

In [16]:
evaluation(DT_model)

[[770 160]
 [122  46]]
accuracy = 74.32%
precesion = 22.33%
recall = 27.38%
f1_score = 24.60%


In [17]:
evaluation(RF_model)

[[916  14]
 [157  11]]
accuracy = 84.43%
precesion = 44.00%
recall = 6.55%
f1_score = 11.40%


In [18]:
evaluation(CB_model)

[[909  21]
 [153  15]]
accuracy = 84.15%
precesion = 41.67%
recall = 8.93%
f1_score = 14.71%


In [19]:
evaluation(XGB_model)

[[887  43]
 [145  23]]
accuracy = 82.88%
precesion = 34.85%
recall = 13.69%
f1_score = 19.66%


C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.