In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('glass.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [4]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [5]:
df.corr()

RI        Na        Mg        Al        Si         K        Ca  \
RI    1.000000 -0.191885 -0.122274 -0.407326 -0.542052 -0.289833  0.810403   
Na   -0.191885  1.000000 -0.273732  0.156794 -0.069809 -0.266087 -0.275442   
Mg   -0.122274 -0.273732  1.000000 -0.481799 -0.165927  0.005396 -0.443750   
Al   -0.407326  0.156794 -0.481799  1.000000 -0.005524  0.325958 -0.259592   
Si   -0.542052 -0.069809 -0.165927 -0.005524  1.000000 -0.193331 -0.208732   
K    -0.289833 -0.266087  0.005396  0.325958 -0.193331  1.000000 -0.317836   
Ca    0.810403 -0.275442 -0.443750 -0.259592 -0.208732 -0.317836  1.000000   
Ba   -0.000386  0.326603 -0.492262  0.479404 -0.102151 -0.042618 -0.112841   
Fe    0.143010 -0.241346  0.083060 -0.074402 -0.094201 -0.007719  0.124968   
Type -0.164237  0.502898 -0.744993  0.598829  0.151565 -0.010054  0.000952   

            Ba        Fe      Type  
RI   -0.000386  0.143010 -0.164237  
Na    0.326603 -0.241346  0.502898  
Mg   -0.492262  0.083060 -0.744993  
Al    0.479404 -0.074402  0.598829  
Si   -0.102151 -0.094201  0.151565  
K    -0.042618 -0.007719 -0.010054  
Ca   -0.112841  0.124968  0.000952  
Ba    1.000000 -0.058692  0.575161  
Fe   -0.058692  1.000000 -0.188278  
Type  0.575161 -0.188278  1.000000

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Type"]= le.fit_transform(df["Type"])

In [7]:
df.head(5)

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     0
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     0
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     0
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     0
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     0

In [8]:
X = df.drop("Type", axis =1)
Y = df['Type']

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=12345)

In [10]:
def build_DT():
    from sklearn.tree import DecisionTreeClassifier
    model = DecisionTreeClassifier()
    model.fit(x_train, y_train)
    return model

In [11]:
def build_RF():
    from sklearn.ensemble import RandomForestClassifier
    model = RandomForestClassifier()
    model.fit(x_train, y_train)
    return model

In [12]:
def build_CB():
    from catboost import CatBoostClassifier
    model = CatBoostClassifier()
    model.fit(x_train, y_train)
    return model

In [13]:
def build_XGB():
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

In [14]:
DT_model = build_DT()
RF_model = build_RF()
CB_model = build_CB()
XGB_model = build_XGB()

Learning rate set to 0.071805
0:	learn: 1.7331565	total: 136ms	remaining: 2m 15s
1:	learn: 1.6521628	total: 146ms	remaining: 1m 12s
2:	learn: 1.5961390	total: 152ms	remaining: 50.4s
3:	learn: 1.5450590	total: 157ms	remaining: 39.2s
4:	learn: 1.5002244	total: 162ms	remaining: 32.3s
5:	learn: 1.4500378	total: 166ms	remaining: 27.6s
6:	learn: 1.3978869	total: 171ms	remaining: 24.3s
7:	learn: 1.3506331	total: 176ms	remaining: 21.8s
8:	learn: 1.3199421	total: 181ms	remaining: 19.9s
9:	learn: 1.2813069	total: 185ms	remaining: 18.4s
10:	learn: 1.2464489	total: 192ms	remaining: 17.2s
11:	learn: 1.2096787	total: 197ms	remaining: 16.2s
12:	learn: 1.1800102	total: 203ms	remaining: 15.4s
13:	learn: 1.1425453	total: 208ms	remaining: 14.7s
14:	learn: 1.1133667	total: 214ms	remaining: 14s
15:	learn: 1.0889689	total: 220ms	remaining: 13.5s
16:	learn: 1.0624006	total: 226ms	remaining: 13s
17:	learn: 1.0384695	total: 231ms	remaining: 12.6s
18:	learn: 1.0116271	total: 237ms	remaining: 12.2s
19:	learn: 0.

C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score
def evaluation(model):
    y_true = y_test
    y_pred = model.predict(x_test)
    cm = confusion_matrix(y_true, y_pred)
    print(cm)
    print(f"accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%")
    print(f"precesion = {precision_score(y_true, y_pred, average='macro')*100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred, average='macro')*100:.2f}%")
    print(f"f1_score = {f1_score(y_true, y_pred, average='macro')*100:.2f}%")

In [16]:
evaluation(DT_model)

[[13  5  3  0  0  0]
 [ 3 14  1  0  3  0]
 [ 2  2  3  0  0  0]
 [ 0  1  0  3  0  0]
 [ 0  0  0  0  3  0]
 [ 1  2  0  0  0  6]]
accuracy = 64.62%
precesion = 69.94%
recall = 68.85%
f1_score = 67.08%


In [17]:
evaluation(RF_model)

[[15  6  0  0  0  0]
 [ 1 19  0  0  1  0]
 [ 4  1  2  0  0  0]
 [ 0  2  0  2  0  0]
 [ 0  0  0  0  3  0]
 [ 1  1  0  1  0  6]]
accuracy = 72.31%
precesion = 79.77%
recall = 67.86%
f1_score = 69.12%


In [18]:
evaluation(CB_model)

[[16  4  1  0  0  0]
 [ 2 18  0  0  1  0]
 [ 4  1  2  0  0  0]
 [ 0  1  0  3  0  0]
 [ 0  0  0  0  3  0]
 [ 1  2  0  0  0  6]]
accuracy = 73.85%
precesion = 80.08%
recall = 72.02%
f1_score = 73.46%


In [19]:
evaluation(XGB_model)

[[13  7  1  0  0  0]
 [ 2 15  1  0  3  0]
 [ 4  1  2  0  0  0]
 [ 0  2  0  2  0  0]
 [ 0  1  0  0  2  0]
 [ 1  2  0  1  0  5]]
accuracy = 60.00%
precesion = 62.54%
recall = 55.69%
f1_score = 56.60%


C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.