In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Zoo.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hair      101 non-null    int64
 1   feathers  101 non-null    int64
 2   eggs      101 non-null    int64
 3   milk      101 non-null    int64
 4   airborne  101 non-null    int64
 5   aquatic   101 non-null    int64
 6   predator  101 non-null    int64
 7   toothed   101 non-null    int64
 8   backbone  101 non-null    int64
 9   breathes  101 non-null    int64
 10  venomous  101 non-null    int64
 11  fins      101 non-null    int64
 12  legs      101 non-null    int64
 13  tail      101 non-null    int64
 14  domestic  101 non-null    int64
 15  catsize   101 non-null    int64
 16  type      101 non-null    int64
dtypes: int64(17)
memory usage: 13.5 KB


In [4]:
df.isna().sum()

hair        0
feathers    0
eggs        0
milk        0
airborne    0
aquatic     0
predator    0
toothed     0
backbone    0
breathes    0
venomous    0
fins        0
legs        0
tail        0
domestic    0
catsize     0
type        0
dtype: int64

In [5]:
df.head(3)

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         0     0     4     0         0        1     1  
1         1         0     0     4     1         0        1     1  
2         0         0     1     0     1         0        0     4

In [6]:
df.corr()

hair  feathers      eggs      milk  airborne   aquatic  \
hair      1.000000 -0.427851 -0.817382  0.878503 -0.198431 -0.473554   
feathers -0.427851  1.000000  0.419248 -0.410761  0.656553 -0.058552   
eggs     -0.817382  0.419248  1.000000 -0.938848  0.376646  0.376244   
milk      0.878503 -0.410761 -0.938848  1.000000 -0.366765 -0.362613   
airborne -0.198431  0.656553  0.376646 -0.366765  1.000000 -0.172638   
aquatic  -0.473554 -0.058552  0.376244 -0.362613 -0.172638  1.000000   
predator -0.154769 -0.104430  0.011605 -0.029721 -0.295181  0.375978   
toothed   0.492531 -0.613631 -0.642150  0.628168 -0.594311  0.053150   
backbone  0.191681  0.231403 -0.340420  0.384958 -0.104718  0.022463   
breathes  0.441149  0.254588 -0.382777  0.423527  0.286039 -0.637506   
venomous -0.104245 -0.145739  0.098689 -0.242449  0.008528  0.087915   
fins     -0.280313 -0.223541  0.164796 -0.156328 -0.251157  0.604492   
legs      0.394009 -0.206686 -0.224918  0.214196  0.043712 -0.360638   
tail      0.048973  0.292569 -0.221090  0.210026  0.009482 -0.034642   
domestic  0.207208  0.031586 -0.155610  0.163928  0.063274 -0.224308   
catsize   0.455020 -0.135934 -0.514650  0.574906 -0.349768 -0.111866   
type     -0.562384 -0.197520  0.661825 -0.723683  0.022677  0.326639   

          predator   toothed  backbone  breathes  venomous      fins  \
hair     -0.154769  0.492531  0.191681  0.441149 -0.104245 -0.280313   
feathers -0.104430 -0.613631  0.231403  0.254588 -0.145739 -0.223541   
eggs      0.011605 -0.642150 -0.340420 -0.382777  0.098689  0.164796   
milk     -0.029721  0.628168  0.384958  0.423527 -0.242449 -0.156328   
airborne -0.295181 -0.594311 -0.104718  0.286039  0.008528 -0.251157   
aquatic   0.375978  0.053150  0.022463 -0.637506  0.087915  0.604492   
predator  1.000000  0.129452  0.051022 -0.262931  0.115391  0.190302   
toothed   0.129452  1.000000  0.575085 -0.065690 -0.062344  0.364292   
backbone  0.051022  0.575085  1.000000  0.207666 -0.246611  0.209499   
breathes -0.262931 -0.065690  0.207666  1.000000 -0.120752 -0.617219   
venomous  0.115391 -0.062344 -0.246611 -0.120752  1.000000 -0.033956   
fins      0.190302  0.364292  0.209499 -0.617219 -0.033956  1.000000   
legs     -0.099723 -0.193476 -0.432856  0.369868  0.022964 -0.605652   
tail      0.018947  0.310368  0.731762  0.088952 -0.162724  0.204349   
domestic -0.309794  0.069430  0.101733  0.124068 -0.003252 -0.093887   
catsize   0.144790  0.344010  0.356976  0.204125 -0.183748  0.031705   
type      0.061179 -0.471527 -0.828845 -0.519308  0.321476  0.099430   

              legs      tail  domestic   catsize      type  
hair      0.394009  0.048973  0.207208  0.455020 -0.562384  
feathers -0.206686  0.292569  0.031586 -0.135934 -0.197520  
eggs     -0.224918 -0.221090 -0.155610 -0.514650  0.661825  
milk      0.214196  0.210026  0.163928  0.574906 -0.723683  
airborne  0.043712  0.009482  0.063274 -0.349768  0.022677  
aquatic  -0.360638 -0.034642 -0.224308 -0.111866  0.326639  
predator -0.099723  0.018947 -0.309794  0.144790  0.061179  
toothed  -0.193476  0.310368  0.069430  0.344010 -0.471527  
backbone -0.432856  0.731762  0.101733  0.356976 -0.828845  
breathes  0.369868  0.088952  0.124068  0.204125 -0.519308  
venomous  0.022964 -0.162724 -0.003252 -0.183748  0.321476  
fins     -0.605652  0.204349 -0.093887  0.031705  0.099430  
legs      1.000000 -0.348295  0.073931  0.068791  0.131693  
tail     -0.348295  1.000000  0.023434  0.243277 -0.631830  
domestic  0.073931  0.023434  1.000000  0.020073 -0.181043  
catsize   0.068791  0.243277  0.020073  1.000000 -0.521030  
type      0.131693 -0.631830 -0.181043 -0.521030  1.000000

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['type'] = le.fit_transform(df['type'])

In [8]:
X = df.drop("type", axis =1)
Y = df['type']

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=12345)

In [10]:
def build_DT():
    from sklearn.tree import DecisionTreeClassifier
    model = DecisionTreeClassifier()
    model.fit(x_train, y_train)
    return model

In [11]:
def build_RF():
    from sklearn.ensemble import RandomForestClassifier
    model = RandomForestClassifier()
    model.fit(x_train, y_train)
    return model

In [12]:
def build_CB():
    from catboost import CatBoostClassifier
    model = CatBoostClassifier()
    model.fit(x_train, y_train)
    return model

In [13]:
def build_XGB():
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

In [14]:
DT_model = build_DT()
RF_model = build_RF()
CB_model = build_CB()
XGB_model = build_XGB()

Learning rate set to 0.069091
0:	learn: 1.8386018	total: 144ms	remaining: 2m 24s
1:	learn: 1.7042914	total: 153ms	remaining: 1m 16s
2:	learn: 1.6410421	total: 161ms	remaining: 53.7s
3:	learn: 1.5633420	total: 170ms	remaining: 42.3s
4:	learn: 1.4697911	total: 178ms	remaining: 35.5s
5:	learn: 1.3909152	total: 187ms	remaining: 31s
6:	learn: 1.3286512	total: 195ms	remaining: 27.7s
7:	learn: 1.2797356	total: 204ms	remaining: 25.3s
8:	learn: 1.2194681	total: 213ms	remaining: 23.5s
9:	learn: 1.1571788	total: 222ms	remaining: 22s
10:	learn: 1.1006986	total: 225ms	remaining: 20.3s
11:	learn: 1.0551556	total: 234ms	remaining: 19.3s
12:	learn: 1.0158954	total: 236ms	remaining: 17.9s
13:	learn: 0.9758481	total: 244ms	remaining: 17.2s
14:	learn: 0.9400097	total: 253ms	remaining: 16.6s
15:	learn: 0.9042817	total: 262ms	remaining: 16.1s
16:	learn: 0.8683808	total: 270ms	remaining: 15.6s
17:	learn: 0.8473463	total: 278ms	remaining: 15.2s
18:	learn: 0.8161790	total: 287ms	remaining: 14.8s
19:	learn: 0.

C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score
def evaluation(model):
    y_true = y_test
    y_pred = model.predict(x_test)
    cm = confusion_matrix(y_true, y_pred)
    print(cm)
    print(f"accuracy = {accuracy_score(y_true, y_pred)*100:.2f}%")
    print(f"precesion = {precision_score(y_true, y_pred, average='macro')*100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred, average='macro')*100:.2f}%")
    print(f"f1_score = {f1_score(y_true, y_pred, average='macro')*100:.2f}%")

In [16]:
evaluation(DT_model)

[[13  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0  2  0  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  1  0  1  0  0]
 [ 0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  1]]
accuracy = 96.77%
precesion = 95.24%
recall = 92.86%
f1_score = 92.38%


In [17]:
evaluation(RF_model)

[[13  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0  1  1  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  1]]
accuracy = 96.77%
precesion = 95.24%
recall = 92.86%
f1_score = 92.38%


In [18]:
evaluation(CB_model)

[[13  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0  1  1  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  1]]
accuracy = 96.77%
precesion = 95.24%
recall = 92.86%
f1_score = 92.38%


In [19]:
evaluation(XGB_model)

[[13  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0  1  1  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  1  0  1  0  0]
 [ 0  0  0  0  0  2  1]
 [ 0  0  0  0  0  0  1]]
accuracy = 90.32%
precesion = 80.95%
recall = 80.95%
f1_score = 77.62%


C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version.