In [1]:
import numpy as np
import pandas as pd

1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.

In [10]:
arr = np.array([1,7,13,105)]


2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [13]:
arr1 = np.array([23,43,56,787])
arr2 = np.array([12,345,45,56])

print(arr1<arr2)
print(arr1<=arr2)
print(arr1>arr2)
print(arr1>=arr2)



[False  True False False]
[False  True False False]
[ True False  True  True]
[ True False  True  True]


3. Write a NumPy program to create an array of integers from 30 to 70.

In [14]:
arr3 = np.arange(30,71)
arr3

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

4. Write a NumPy program to create an array of all even integers from 20 to 80.

In [20]:
arr4 = [value for value in np.arange(20,81) if value%2==0]
print(arr4)

[20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80]


5. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [21]:
arr5 = [value for value in np.arange(20,81) if value%2!=0]
print(arr5)

[21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79]


6. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.

In [24]:
arr6 = np.random.randint(10,40,15)
print(arr6)

[25 19 29 35 24 30 27 35 15 15 16 31 21 21 15]



7. Write a NumPy program to generate an array of 10 random numbers from 30 to 50.


In [25]:
arr7 = np.random.randint(30,50,10)
print(arr7)

[38 36 43 30 36 30 46 40 36 46]



8. Create any two arrays & perform various mathematical operations.
    i.e. Addition, Substraction, Multiplication, Divide.

In [27]:
arr8 = np.array([23,43,56,787])
arr9 = np.array([12,345,45,56])

print(arr8+arr9)
print(arr8-arr9)
print(arr8*arr9)
print(arr8/arr9)


[ 35 388 101 843]
[  11 -302   11  731]
[  276 14835  2520 44072]
[ 1.91666667  0.12463768  1.24444444 14.05357143]



9. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [43]:
matrix1 = np.arange(10,22).reshape((3,4))

print(matrix1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]



10. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [45]:
matrix2 = np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)
print(matrix2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]



11. Write a NumPy program to find the number of rows and columns in a given matrix. 

In [50]:
matrix2 = np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)

row,col = matrix2.shape
print(row)
print(col)


3
3



12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [56]:
matrix3 = np.zeros(25).reshape(5,5)
# print(matrix3)

for i in range(0,5):
    matrix3[i][i]=i+1

print(matrix3)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]



13. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [67]:
matrix5 = np.random.random(27).reshape(3,3,3)
print(matrix5)

[[[3.99977080e-01 6.22873849e-01 6.53114202e-01]
  [5.10002942e-01 4.26868669e-01 9.90867432e-01]
  [2.82584074e-04 7.31230306e-01 1.12351402e-01]]

 [[1.80520586e-01 4.51420102e-01 9.80546807e-01]
  [2.85570027e-01 8.88200281e-01 5.52936681e-01]
  [7.10751817e-01 9.73755314e-01 9.08370850e-01]]

 [[7.08770345e-01 2.33102360e-01 3.90249730e-01]
  [8.28303588e-01 1.33739032e-01 5.55707923e-01]
  [3.72551455e-02 4.84232997e-01 9.42438357e-01]]]



14. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.


In [68]:
matrix4 = np.random.random(24).reshape(2,3,4)
print(matrix4)

[[[0.71903174 0.98531696 0.59608889 0.98081408]
  [0.24226157 0.8559433  0.39240858 0.59463254]
  [0.262786   0.27780333 0.06428195 0.27739315]]

 [[0.71025626 0.11808117 0.93517808 0.14290745]
  [0.58557441 0.43993455 0.34080622 0.010859  ]
  [0.25759285 0.84790602 0.82865677 0.34946417]]]


15. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.


In [78]:
list1 = [1,2,3,44,5,6,78,89,9]
arr01 = np.array(list1)
print(arr01)
print(arr01.ndim)

[ 1  2  3 44  5  6 78 89  9]
1


16. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.


In [80]:
matrix6 = np.arange(2,11).reshape(3,3)
print(matrix6)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


17. Write a NumPy program to create an array with values ranging from 12 to 38.

In [81]:
arr02 = np.arange(12,39)
print(arr02)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


18. Write a NumPy program to reverse an array (the first element becomes the last).

In [87]:
arr02 = np.arange(12,39)
print(arr02)
print()
print(f"reversed array:- {arr02[::-1]}")

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]

reversed array:- [38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


19. Write a NumPy program to get the element-wise remainder of an array of division.

In [88]:
list1 = [1,2,3,44,5,6,78,89,9]
arr01 = np.array(list1)
print(arr01%23)

[ 1  2  3 21  5  6  9 20  9]


20. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [89]:
arr03 = np.arange(20,51)
print(arr03%3)

[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


21. Write a Pandas program to create a dataframe from a dictionary and display it.

In [103]:
# dict1 = {1:"one",2:"two",3:"three"}
# df =pd.DataFrame(dict1)
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}

df = pd.DataFrame(data)

print(df)


      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles



22. i) Create a list of empids and names (10 employees).
   ii) Convert list into Series.
   iii) Print type of Series.
   iv) Convert Series into DataFrame.
   v) a) Display all records.
      b) Display first five records.
      c) Display last five records.
      d) Display first two and last two records.
      e) Display name of 5th employee.
      f) Display record of 4th employee.
   vi) Save the record in csv file (MyRecord.csv)

 i) Create a list of empids and names (10 employees).

In [105]:
empid = [1,2,3,4,5,6,7,8,9,10]
names = ['A','B','C','D','E','F','G','H','I','J']

 ii) Convert list into Series.

In [159]:
series = pd.Series(names,empid)
print(series)

1     A
2     B
3     C
4     D
5     E
6     F
7     G
8     H
9     I
10    J
dtype: object


iii) Print type of Series

In [160]:
print(type(series))

<class 'pandas.core.series.Series'>


iv) Convert Series into DataFrame. 

In [161]:
df1 = series.to_frame()

print(df1)

    0
1   A
2   B
3   C
4   D
5   E
6   F
7   G
8   H
9   I
10  J


 v) a) Display all records. b) Display first five records. c) Display last five records. d) Display first two and last two records. e) Display name of 5th employee. f) Display record of 4th employee. vi) Save the record in csv file (MyRecord.csv)

In [162]:
print(df1)

    0
1   A
2   B
3   C
4   D
5   E
6   F
7   G
8   H
9   I
10  J


In [163]:
df1.head(5)


0
1  A
2  B
3  C
4  D
5  E

In [165]:
df1.tail(5)

0
6   F
7   G
8   H
9   I
10  J

In [164]:
print(df1.head(2))
print(df1.tail(2))

   0
1  A
2  B
    0
9   I
10  J


In [166]:
df1.loc[5]

0    E
Name: 5, dtype: object

In [147]:
df1.loc[4]


0    D
Name: 4, dtype: object

In [167]:
df1.to_csv("MyRecord.csv")

23. i) Read the MyRecord.csv file.
    ii) Create a new column Salary.


In [168]:
df2 = pd.read_csv("MyRecord.csv")
df2

Unnamed: 0  0
0           1  A
1           2  B
2           3  C
3           4  D
4           5  E
5           6  F
6           7  G
7           8  H
8           9  I
9          10  J

In [169]:
df2['salary']=[12,34,45,45,45,13,23,23,23,23]
df2.columns = ['empid', 'name','salary']
print(df2)


   empid name  salary
0      1    A      12
1      2    B      34
2      3    C      45
3      4    D      45
4      5    E      45
5      6    F      13
6      7    G      23
7      8    H      23
8      9    I      23
9     10    J      23



24. Refer the dataset "Advertising.csv" and perform following tasks.
i) Read the dataset "Advertising.csv" in data frame.

ii) Print first five records of dataset.

iii) print last five records from dataset.

iv) display the column names of the dataset.

v) display last three records from dataset.

vi) display the information about the dataset and analyse the data.

vii) display data types of each columns.
 
viii) check for null values in the dataset and display the sum of null values inside the column.

ix) drop a column 'radio' from a dataset and display first ten records.

x) increase the sales by 10% and add a new column "updated_sales" in dataframe.

xi) display shape of data.

In [210]:
df4 = pd.read_csv("Advertising.csv")
print(df4)

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]


In [200]:
df4.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [201]:
df4.tail()

TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [202]:
df4.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [203]:
df4.tail(3)

TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [204]:
df4.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [205]:
df4.dtypes

TV           float64
radio        float64
newspaper    float64
sales        float64
dtype: object

In [206]:
print(df4.isna())
print()
print(df4.isna().sum())

        TV  radio  newspaper  sales
0    False  False      False  False
1    False  False      False  False
2    False  False      False  False
3    False  False      False  False
4    False  False      False  False
..     ...    ...        ...    ...
195  False  False      False  False
196  False  False      False  False
197  False  False      False  False
198  False  False      False  False
199  False  False      False  False

[200 rows x 4 columns]

TV           0
radio        0
newspaper    0
sales        0
dtype: int64


In [211]:
print(df4.head(10))
df4=df4.drop(columns=['radio'])
print(df4.head(10))




      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9
5    8.7   48.9       75.0    7.2
6   57.5   32.8       23.5   11.8
7  120.2   19.6       11.6   13.2
8    8.6    2.1        1.0    4.8
9  199.8    2.6       21.2   10.6
      TV  newspaper  sales
0  230.1       69.2   22.1
1   44.5       45.1   10.4
2   17.2       69.3    9.3
3  151.5       58.5   18.5
4  180.8       58.4   12.9
5    8.7       75.0    7.2
6   57.5       23.5   11.8
7  120.2       11.6   13.2
8    8.6        1.0    4.8
9  199.8       21.2   10.6


In [212]:
df4['updates_sales'] = df4['sales']*1.1
print(df4)

        TV  newspaper  sales  updates_sales
0    230.1       69.2   22.1          24.31
1     44.5       45.1   10.4          11.44
2     17.2       69.3    9.3          10.23
3    151.5       58.5   18.5          20.35
4    180.8       58.4   12.9          14.19
..     ...        ...    ...            ...
195   38.2       13.8    7.6           8.36
196   94.2        8.1    9.7          10.67
197  177.0        6.4   12.8          14.08
198  283.6       66.2   25.5          28.05
199  232.1        8.7   13.4          14.74

[200 rows x 4 columns]


In [213]:
df4.shape

(200, 4)

25. Refer the dataset "Salaries.csv" and perform following tasks.

i) Read the dataset in dataframe.

In [220]:
%config IPCompleter.greedy=True


In [222]:
df5 = pd.read_csv("Salaries .csv")


ii) display first five records.

In [223]:
df5.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

iii) display first ten records.

In [225]:
df5.head(10)

rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

iv) display last five records.

In [226]:
df5.tail()

rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

v) display last ten records.

In [228]:
df5.tail(10)

rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

vi) display the columns inside the dataset.

In [229]:
df5.columns


Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

vii) display shape of data.


In [230]:
df5.shape


(78, 6)

viii) describe the dataset.


In [233]:
df5.describe()

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

ix) display the information about the dataset and analyse the data.

In [236]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64 
 3   service     78 non-null     int64 
 4   sex         78 non-null     object
 5   salary      78 non-null     int64 
dtypes: int64(3), object(3)
memory usage: 3.8+ KB


x) display types of each columns.

In [239]:
df5.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

xi) Find out maximum,minimum,mean,median,standard deviation value of each column.

In [240]:
print(df5.describe())

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000



xii) check for null values in the dataset and display the sum of null values inside the column.

In [242]:
print(df5.isna())
print(df5.isna().sum())

     rank  discipline    phd  service    sex  salary
0   False       False  False    False  False   False
1   False       False  False    False  False   False
2   False       False  False    False  False   False
3   False       False  False    False  False   False
4   False       False  False    False  False   False
..    ...         ...    ...      ...    ...     ...
73  False       False  False    False  False   False
74  False       False  False    False  False   False
75  False       False  False    False  False   False
76  False       False  False    False  False   False
77  False       False  False    False  False   False

[78 rows x 6 columns]
rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64


xiii) drop all null values.

In [244]:
df5.dropna()

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

xiv) a) display records whose salary is greater than 50000.
     b) display records whose salary is less than 20000.
     c) display records whose salary is between 20000 to 50000.
     d) display records whose salary is greater than 100000.
     e) display records whose salary is less than 100000.


In [255]:
print(df5[df5['salary'] > 50000])
    

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]


  b) display records whose salary is less than 20000.

In [256]:
print(df5[df5['salary'] <20000])

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []


 c) display records whose salary is between 20000 to 50000.

In [265]:
print(df5[(df5['salary']>20000) & (df5['salary'] <50000)])

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []


     d) display records whose salary is greater than 100000.

In [267]:
print(df5[df5['salary']>100000])

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
7        Prof          A   18       18    Male  126300
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
30  AssocP

     e) display records whose salary is less than 100000.

In [268]:
print(df5[df5['salary']<100000])

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
6   AssocProf          A   20       17    Male   81285
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
12   AsstProf          B    1        0    Male   88000
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
38   AsstProf          B    4        3    Male   91000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
46   AsstP

xv)  a) display records whose discipline is A.

In [269]:
print(df5[df5['discipline']=='A'])

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
32       Prof          A   27       19    Male  103275
37       P

  b) display records whose discipline is B.

In [270]:
print(df5[df5['discipline']=='B'])

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
4        Prof          B   20       18    Male  104800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
33       Prof          B   18       18    Male  120000
34  AssocP

     c) display records whose service is greater than 10.

In [271]:
print(df5[df5['service']>10])

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       P

d) display records whose service is less than 5.

In [272]:
print(df5[df5['service']<5])

        rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
15      Prof          B   17        3    Male  150480
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
52      Prof          A   12        0  Female  105000
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
68  AsstProf          A    4

xvi) a) display records of phd and salary.

In [276]:
print(df5[['phd','salary']])

    phd  salary
0    56  186960
1    12   93000
2    23  110515
3    40  131205
4    20  104800
..  ...     ...
73   18  105450
74   19  104542
75   17  124312
76   28  109954
77   23  109646

[78 rows x 2 columns]


     b) display records of rank, sex and salary.

In [277]:
print(df5[['rank','sex','salary']])

         rank     sex  salary
0        Prof    Male  186960
1        Prof    Male   93000
2        Prof    Male  110515
3        Prof    Male  131205
4        Prof    Male  104800
..        ...     ...     ...
73       Prof  Female  105450
74  AssocProf  Female  104542
75       Prof  Female  124312
76       Prof  Female  109954
77       Prof  Female  109646

[78 rows x 3 columns]


     c) display records without salary.

In [282]:
print(df5[[col for col in df5.columns if col !='salary']])

         rank discipline  phd  service     sex
0        Prof          B   56       49    Male
1        Prof          A   12        6    Male
2        Prof          A   23       20    Male
3        Prof          A   40       31    Male
4        Prof          B   20       18    Male
..        ...        ...  ...      ...     ...
73       Prof          B   18       10  Female
74  AssocProf          B   19        6  Female
75       Prof          B   17       17  Female
76       Prof          A   28       14  Female
77       Prof          A   23       15  Female

[78 rows x 5 columns]


     d) display first 50 records with rank,service and salary.

In [284]:
print(df5[['rank','service','salary']].head(50))

         rank  service  salary
0        Prof       49  186960
1        Prof        6   93000
2        Prof       20  110515
3        Prof       31  131205
4        Prof       18  104800
5        Prof       20  122400
6   AssocProf       17   81285
7        Prof       18  126300
8        Prof       19   94350
9        Prof       51   57800
10       Prof       33  128250
11       Prof       23  134778
12   AsstProf        0   88000
13       Prof       33  162200
14       Prof       19  153750
15       Prof        3  150480
16   AsstProf        3   75044
17   AsstProf        0   92000
18       Prof        7  107300
19       Prof       27  150500
20   AsstProf        4   92000
21       Prof       30  103106
22   AsstProf        2   73000
23   AsstProf        0   85000
24       Prof       23   91100
25       Prof       31   99418
26       Prof       19  148750
27       Prof       43  155865
28   AsstProf        2   91300
29       Prof       20  123683
30  AssocProf        7  107008
31      

     e) display records whose rank is Prof.

In [285]:
print(df5[df5['rank']=='Prof'])

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418


     f) display records whose rank is AssocProf. 

In [286]:
print(df5[df5['rank']=='AssocProf'])

         rank discipline  phd  service     sex  salary
6   AssocProf          A   20       17    Male   81285
30  AssocProf          B    9        7    Male  107008
34  AssocProf          B   12        8    Male  119800
41  AssocProf          A   13        8  Female   74830
47  AssocProf          B   11       11  Female  103613
54  AssocProf          A   25       22  Female   62884
56  AssocProf          A   10        8  Female   77500
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
64  AssocProf          A   26       24  Female   73300
71  AssocProf          B   12        9  Female   71065
74  AssocProf          B   19        6  Female  104542
