In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('framingham.csv')

In [3]:
df.describe()

male          age    education  currentSmoker   cigsPerDay  \
count  4240.000000  4240.000000  4135.000000    4240.000000  4211.000000   
mean      0.429245    49.580189     1.979444       0.494104     9.005937   
std       0.495027     8.572942     1.019791       0.500024    11.922462   
min       0.000000    32.000000     1.000000       0.000000     0.000000   
25%       0.000000    42.000000     1.000000       0.000000     0.000000   
50%       0.000000    49.000000     2.000000       0.000000     0.000000   
75%       1.000000    56.000000     3.000000       1.000000    20.000000   
max       1.000000    70.000000     4.000000       1.000000    70.000000   

            BPMeds  prevalentStroke  prevalentHyp     diabetes      totChol  \
count  4187.000000      4240.000000   4240.000000  4240.000000  4190.000000   
mean      0.029615         0.005896      0.310613     0.025708   236.699523   
std       0.169544         0.076569      0.462799     0.158280    44.591284   
min       0.000000         0.000000      0.000000     0.000000   107.000000   
25%       0.000000         0.000000      0.000000     0.000000   206.000000   
50%       0.000000         0.000000      0.000000     0.000000   234.000000   
75%       0.000000         0.000000      1.000000     0.000000   263.000000   
max       1.000000         1.000000      1.000000     1.000000   696.000000   

             sysBP        diaBP          BMI    heartRate      glucose  \
count  4240.000000  4240.000000  4221.000000  4239.000000  3852.000000   
mean    132.354599    82.897759    25.800801    75.878981    81.963655   
std      22.033300    11.910394     4.079840    12.025348    23.954335   
min      83.500000    48.000000    15.540000    44.000000    40.000000   
25%     117.000000    75.000000    23.070000    68.000000    71.000000   
50%     128.000000    82.000000    25.400000    75.000000    78.000000   
75%     144.000000    90.000000    28.040000    83.000000    87.000000   
max     295.000000   142.500000    56.800000   143.000000   394.000000   

        TenYearCHD  
count  4240.000000  
mean      0.151887  
std       0.358953  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4240 non-null   int64  
 1   age              4240 non-null   int64  
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64  
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64  
 7   prevalentHyp     4240 non-null   int64  
 8   diabetes         4240 non-null   int64  
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 530.1 KB


In [5]:
df.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.isna().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [8]:
df.corr()

male       age  education  currentSmoker  cigsPerDay  \
male             1.000000 -0.024412   0.017729       0.206114    0.330322   
age             -0.024412  1.000000  -0.159499      -0.210771   -0.189295   
education        0.017729 -0.159499   1.000000       0.025251    0.013790   
currentSmoker    0.206114 -0.210771   0.025251       1.000000    0.773913   
cigsPerDay       0.330322 -0.189295   0.013790       0.773913    1.000000   
BPMeds          -0.052124  0.134732  -0.013739      -0.051923   -0.046504   
prevalentStroke -0.002312  0.050893  -0.030386      -0.038150   -0.036286   
prevalentHyp     0.001424  0.306239  -0.078828      -0.108078   -0.070460   
diabetes         0.013819  0.109092  -0.039627      -0.041849   -0.036961   
totChol         -0.070321  0.268252  -0.013522      -0.051034   -0.030400   
sysBP           -0.045358  0.388267  -0.124360      -0.134428   -0.094781   
diaBP            0.051872  0.208283  -0.058059      -0.115955   -0.056746   
BMI              0.073111  0.137511  -0.137555      -0.159821   -0.087395   
heartRate       -0.115285 -0.002722  -0.064214       0.050841    0.064030   
glucose          0.002940  0.118349  -0.031998      -0.053242   -0.053726   
TenYearCHD       0.091688  0.233983  -0.063279       0.019165    0.052014   

                   BPMeds  prevalentStroke  prevalentHyp  diabetes   totChol  \
male            -0.052124        -0.002312      0.001424  0.013819 -0.070321   
age              0.134732         0.050893      0.306239  0.109092  0.268252   
education       -0.013739        -0.030386     -0.078828 -0.039627 -0.013522   
currentSmoker   -0.051923        -0.038150     -0.108078 -0.041849 -0.051034   
cigsPerDay      -0.046504        -0.036286     -0.070460 -0.036961 -0.030400   
BPMeds           1.000000         0.113125      0.262910  0.049066  0.094083   
prevalentStroke  0.113125         1.000000      0.066057  0.009625  0.012736   
prevalentHyp     0.262910         0.066057      1.000000  0.080556  0.166655   
diabetes         0.049066         0.009625      0.080556  1.000000  0.048451   
totChol          0.094083         0.012736      0.166655  0.048451  1.000000   
sysBP            0.271263         0.061070      0.697675  0.102552  0.219925   
diaBP            0.199630         0.055834      0.617734  0.050686  0.174422   
BMI              0.105642         0.036496      0.302949  0.089009  0.121056   
heartRate        0.012889        -0.017019      0.146818  0.060984  0.093053   
glucose          0.054232         0.016061      0.086942  0.614820  0.049884   
TenYearCHD       0.089152         0.048366      0.181387  0.093431  0.091338   

                    sysBP     diaBP       BMI  heartRate   glucose  TenYearCHD  
male            -0.045358  0.051872  0.073111  -0.115285  0.002940    0.091688  
age              0.388267  0.208283  0.137511  -0.002722  0.118349    0.233983  
education       -0.124360 -0.058059 -0.137555  -0.064214 -0.031998   -0.063279  
currentSmoker   -0.134428 -0.115955 -0.159821   0.050841 -0.053242    0.019165  
cigsPerDay      -0.094781 -0.056746 -0.087395   0.064030 -0.053726    0.052014  
BPMeds           0.271263  0.199630  0.105642   0.012889  0.054232    0.089152  
prevalentStroke  0.061070  0.055834  0.036496  -0.017019  0.016061    0.048366  
prevalentHyp     0.697675  0.617734  0.302949   0.146818  0.086942    0.181387  
diabetes         0.102552  0.050686  0.089009   0.060984  0.614820    0.093431  
totChol          0.219925  0.174422  0.121056   0.093053  0.049884    0.091338  
sysBP            1.000000  0.786669  0.330917   0.184797  0.134651    0.222821  
diaBP            0.786669  1.000000  0.385348   0.178744  0.063540    0.150124  
BMI              0.330917  0.385348  1.000000   0.074131  0.083683    0.082055  
heartRate        0.184797  0.178744  0.074131   1.000000  0.097074    0.020514  
glucose          0.134651  0.063540  0.083683   0.097074  1.000000    0.121990  
TenYearCHD       0.222821  0.150124  0.082055   0.0205

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3658 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             3658 non-null   int64  
 1   age              3658 non-null   int64  
 2   education        3658 non-null   float64
 3   currentSmoker    3658 non-null   int64  
 4   cigsPerDay       3658 non-null   float64
 5   BPMeds           3658 non-null   float64
 6   prevalentStroke  3658 non-null   int64  
 7   prevalentHyp     3658 non-null   int64  
 8   diabetes         3658 non-null   int64  
 9   totChol          3658 non-null   float64
 10  sysBP            3658 non-null   float64
 11  diaBP            3658 non-null   float64
 12  BMI              3658 non-null   float64
 13  heartRate        3658 non-null   float64
 14  glucose          3658 non-null   float64
 15  TenYearCHD       3658 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 485.8 KB


In [10]:
X = df.drop(['TenYearCHD'], axis=1)
Y = df['TenYearCHD']

In [11]:
from sklearn.model_selection import train_test_split

# split the data into train and test datasets
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=12345)

In [12]:
def build_logistic_regression():
    from sklearn.linear_model import LogisticRegressionCV
    
    # create a model
    model = LogisticRegressionCV()

    # train the model
    model.fit(x_train, y_train)

    return model

In [13]:
def svmModel():
    from sklearn.svm import SVC
    model = SVC()
    model.fit(x_train,y_train)
    return model

In [14]:
def knn():
    from sklearn.neighbors import KNeighborsClassifier
    model = KNeighborsClassifier(n_neighbors=7)
    model.fit(x_train,y_train)
    return model

In [15]:
logi_model = build_logistic_regression()

knn_model = knn()
svm_model= svmModel()

C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\subha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

## Evaluation

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
def evaluate(model):
    y_true = y_test
    y_pred = model.predict(x_test)
      
    cm = confusion_matrix(y_true, y_pred)
    print(cm)

    
    print(f"accuracy = {accuracy_score(y_true, y_pred) * 100:.2f}%")
    print(f"precision = {precision_score(y_true, y_pred) * 100:.2f}%")
    print(f"recall = {recall_score(y_true, y_pred) * 100:.2f}%")
    print(f"F1 score = {f1_score(y_true, y_pred) * 100:.2f}%")

In [17]:
evaluate(logi_model)

[[923   7]
 [152  16]]
accuracy = 85.52%
precision = 69.57%
recall = 9.52%
F1 score = 16.75%


In [18]:
evaluate(knn_model)

[[913  17]
 [153  15]]
accuracy = 84.52%
precision = 46.88%
recall = 8.93%
F1 score = 15.00%


In [19]:
evaluate(svm_model)

[[928   2]
 [166   2]]
accuracy = 84.70%
precision = 50.00%
recall = 1.19%
F1 score = 2.33%
